apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: date
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dateperminute
              image: eagle.example.com:5000/busybox
              args:
              - /bin/sh
              - -c
              - date; sleep 10
          restartPolicy: OnFailure
