apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "web"
  template:
    metadata:
      labels:
        app: "web"
    spec:
      containers:
      - name: "apache-frontend"
        image: "eagle.example.com:5000/httpd:secure"
        ports:
        - containerPort: 80
        env:
        - name: DB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: db-root-pwd
              key: dbpwd
        volumeMounts:
        - name: webenvvol
          mountPath: /etc/httpd/conf.d/env.conf
          subPath: env.conf
        - name: webroot
          mountPath: /var/www/html
      volumes:
      - name: webenvvol
        configMap:
          name: webenv
      - name: webroot
        persistentVolumeClaim:
          claimName: webclaim
