apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "web"
  template:
    metadata:
      labels:
        app: "web"
    spec:
      initContainers:
      - name: "homepage"
        image:  "eagle.example.com:5000/busybox:1.30.1"
        command: ['sh','-c','sleep 10;echo $(hostname) >> /prepare/index.html']
        volumeMounts:
        - mountPath: "/prepare"
          name: "webroot"
      - name: "checkdb"
        image: "eagle.example.com:5000/mysql:v2"
        command: ['sh','-c',"until mysql -h dbserver-2.database -u root -p$DB_ROOT_PWD -e 'show status';do sleep 10;done"]
        env:
        - name: DB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: db-root-pwd
              key: dbpwd
      containers:
      - name: "apache-frontend"
        image: "eagle.example.com:5000/httpd:secure"
        ports:
        - containerPort: 80
        env:
        - name: DB_ROOT_PWD
          valueFrom:
            secretKeyRef:
              name: db-root-pwd
              key: dbpwd
        volumeMounts:
        - name: webenvvol
          mountPath: /etc/httpd/conf.d
        - name: webroot
          mountPath: /var/www/html
      volumes:
      - name: webenvvol
        configMap:
          name: webenv
      - name: webroot
        persistentVolumeClaim:
          claimName: webclaim
