apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "dbserver-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "db"
  template:
    metadata:
      labels:
        app: "db"
    spec:
      containers:
      - name: "db-backend"
        image: "eagle.example.com:5000/mysql"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-root-pwd
              key: dbpwd
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: configvol
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: configvol
          configMap:
            name: dbinit
