apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webv2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web"
      version: v2
  template:
    metadata:
      labels:
        app: "web"
        version: v2
    spec:
      containers:
      - name: "apache-frontend"
        image: "eagle.example.com:5000/httpd:dns"
        ports:
        - containerPort: 80
