apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "web"
  template:
    metadata:
      labels:
        app: "web"
    spec:
      containers:
      - name: "apache-frontend"
        image: "eagle.example.com:5000/httpd:webapp"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: myregkey
