apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-backend
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ingress-default-backend
          servicePort: http
