apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
spec:
  limits:
  - type: Pod
    max:
      cpu: 500m
      memory: 750Mi
    min:
      cpu: 50m
      memory: 50Mi
  - type: Container
    default:
      cpu: 100m
      memory: 150Mi
    defaultRequest:
      cpu: 100m
      memory: 150Mi
    max:
      cpu: 500m
      memory: 750Mi
    min:
      cpu: 50m
      memory: 50Mi
#  - type: PersistentVolumeClaim
#    max:
#      storage: 2Gi
#    min:
#      storage: 1Gi
