apiVersion: "v1"
kind: "Service"
metadata:
  name: "mydbsvc"
  labels:
    svc: "mydb"
spec:
  ports:
  - protocol: "TCP"
    port: 3306
  selector:
    app: "mydb"

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mydb-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mydb"
  template:
    metadata:
      labels:
        app: "mydb"
    spec:
      containers:
      - name: "mydbcontainer"
        image: "eagle.example.com:5000/mysql"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: redhat
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: myregkey

