apiVersion: "v1"
kind: "Pod"
metadata:
  name: "bigapp"
  labels:
    app: "bigapp"
  annotations:
    k8s.v1.cni.cncf.io/networks: "macvlan-static"
spec:
  containers:
  - name: "db-backend"
    image: "eagle.example.com:5000/mysql"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "redhat"
    ports:
    - containerPort: 3306
  - name: "web-frontend"
    image: "eagle.example.com:5000/httpd:webapp"
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: myregkey
