apiVersion: "v1"
kind: "Pod"
metadata:
  name: "bigapp"
  labels:
    app: "bigapp"
spec:
  containers:
  - name: "db-backend"
    image: "eagle.example.com:5000/mysql"
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "redhat"
    ports:
    - containerPort: 3306
    securityContext:
      privileged: true
  - name: "web-frontend"
    image: "eagle.example.com:5000/httpd:webapp"
    ports:
    - containerPort: 80
      hostPort: 80
    securityContext:
      privileged: true
  imagePullSecrets:
  - name: myregkey
