apiVersion: "v1"
kind: "Pod"
metadata:
  name: "webserver"
  labels:
    app: "web"
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-static
spec:
  containers:
  - name: "apache-frontend"
    image: "eagle.example.com:5000/httpd:webapp"
    ports:
    - containerPort: 80
