apiVersion: v1
kind: Pod
metadata:
  name: static
spec:
  containers:
  - image: eagle.example.com:5000/busybox
    imagePullPolicy: IfNotPresent
    name: sleepycat
    command:
    - sh
    - -c
    - while true;do echo sleepy;sleep 10;done
  
