apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "nfspv"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: "Recycle"
  nfs:
    server: "eagle.example.com"
    path: "/shared"
