apiVersion: "v1"
kind: "Service"
metadata:
  name: "webv2-service-lb"
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "web"
    version: v2
