apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-service-lb"
  #  annotations:
  #    metallb.universe.tf/address-pool: default
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "web"
