apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-service-lb"
spec:
  type: "LoadBalancer"
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "web"
  topologyKeys:
  - "kubernetes.io/hostname"
  - "*"
