apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-service"
spec:
  externalTrafficPolicy: Local
  type: "NodePort"
  ports:
  - protocol: "TCP"
    port: 80
    nodePort: 30000
  selector:
    app: "web"
