apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-service-lb-static"
spec:
  type: "LoadBalancer"
  loadBalancerIP: 10.10.10.50
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "web"
