apiVersion: "v1"
kind: "Service"
metadata:
  name: "database-service"
spec:
  type: "ClusterIP"
  ports:
  - protocol: "TCP"
    port: 3306
  selector:
    app: "db"
  sessionAffinity: ClientIP
  topologyKeys:
  - "kubernetes.io/hostname"
