apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "dbserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "db"
  serviceName: "database"
  template:
    metadata:
      labels:
        app: "db"
    spec:
      containers:
      - name: "db-backend"
        image: "eagle.example.com:5000/mysql:v2"
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "redhat"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: configvol
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: configvol
          configMap:
            name: dbinit
