apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "web1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "web"
      version: v1
  template:
    metadata:
      labels:
        app: "web"
        version: v1
    spec:
      containers:
      - name: "apache-frontend"
        image: "eagle.example.com:5000/httpd:dns"
        ports:
        - containerPort: 80
