apiVersion: "v1"
kind: "Pod"
metadata:
  name: "lpv-test"
spec:
  containers:
  - name: "apache-frontend"
    image: "eagle.example.com:5000/httpd:dns"
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/var/www/html"
      name: "webroot"
  volumes:
  - name: "webroot"
    persistentVolumeClaim:
      claimName: "lpvc"
