apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-0
  labels:
    lpvs: "galera"
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-1
  labels:
    lpvs: "galera"
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mysql-2
  labels:
    lpvs: "galera"
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
