apiVersion: "v1"
kind: "Pod"
metadata:
  name: "probe"
  labels:
    app: "probe"
spec:
  containers:
  - name: "probe"
    image: "eagle.example.com:5000/probe:0.1"
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 3
