apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: installed-state
  namespace: istio-system
spec:
  profile: demo
  hub: docker.io/istio
  tag: 1.7.4
  meshConfig:
    outboundTrafficPolicy:
      mode: ALLOW_ANY
  values:
    global:
      imagePullPolicy: IfNotPresent
